### ISSUE TITLE
BUG: `weaviate.Client` is Deprecated and Should be Replaced with `weaviate.WeaviateClient`

### ISSUE THREAD

**Issue by jspeed-meyers** [weaviate/weaviate-benchmarking#22]
While troubleshooting on issue #19, I also ran into this issue:

```
DeprecationWarning: Dep016: Python client v3 `weaviate.Client(...)` connections and methods are deprecated. Update
            your code to use Python client v4 `weaviate.WeaviateClient` connections and methods.

            For Python Client v4 usage, see: https://weaviate.io/developers/weaviate/client-libraries/python
            For code migration, see: https://weaviate.io/developers/weaviate/client-libraries/python/v3_v4_migration
            
  warnings.warn(
<weaviate.client.Client object at 0x1022852b0>
``` 

This issue can be traced back to:

https://github.com/weaviate/weaviate-benchmarking/blob/5ed75e79cb91bdae78935941c2660305b1535b17/benchmark-scripts/src/functions.py#L252-L257

I'm starting to think that this benchmarking project has a number of outdated components. I wonder if this repo documentation should be changed to make it clear to user that this repo is not maintained, on the assumption it is intentionally not maintained?

**Comment by ZJL0111** [comment]
hi， meyers， this issue may help you  [https://github.com/langchain-ai/langchain/pull/20443 
](url)
